name: practice_repository
description: A repository that handles pratice related requests.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies: 
  sorted_list: ^1.0.0
  practice_api:
    path: ../practice_api
  common: 
    path: ../common

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
  # build_runner: ^2.3.2
