name: firebase_practice_api
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  practice_api:
    path: ../practice_api
  firebase_core: ^1.22.0
  firebase_database: ^9.1.4


dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
