name: practice_api
description: The interface and models proving accsess to the swimmers durring a practice
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.6.0
  meta: ^1.3.0
  uuid: ^3.0.4

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
