name: entities
description: Common Entities
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  common: 
    path: ../common
  json_serializable: ^6.5.4

  equatable: ^2.0.5
  build_runner: ^2.3.2

dev_dependencies:
  # build_runner: ^2.3.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
