// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSzdXvQN2DDnxBJFs0kyRz7qaZODslCKE',
    appId: '1:589959329423:web:052c8ccb7c6ea9d268a2fa',
    messagingSenderId: '589959329423',
    projectId: 'swimtimer-36014',
    authDomain: 'swimtimer-36014.firebaseapp.com',
    databaseURL: 'https://swimtimer-36014-default-rtdb.firebaseio.com',
    storageBucket: 'swimtimer-36014.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY6yVmjLhk8aExfBF097h54_0CFln7EkY',
    appId: '1:589959329423:android:5b9346e517319af168a2fa',
    messagingSenderId: '589959329423',
    projectId: 'swimtimer-36014',
    databaseURL: 'https://swimtimer-36014-default-rtdb.firebaseio.com',
    storageBucket: 'swimtimer-36014.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDROe4ALEa5mxRn4XsPTUPXk6Lg_QSuOS4',
    appId: '1:589959329423:ios:c259f324dd7e1bae68a2fa',
    messagingSenderId: '589959329423',
    projectId: 'swimtimer-36014',
    databaseURL: 'https://swimtimer-36014-default-rtdb.firebaseio.com',
    storageBucket: 'swimtimer-36014.appspot.com',
    iosClientId: '589959329423-2rbo5747s0848gn43mentr75nqv8769i.apps.googleusercontent.com',
    iosBundleId: 'com.example.swimTimer',
  );
}
